### ISSUE TITLE
Send Email

### ISSUE THREAD

**Issue by toshiro9117** [InJeCTrL/NeedFree#2]
Add Feature to send an email.

**Comment by InJeCTrL** [comment]
Hi, thank you for supporting **NeedFree**!
Since sending emails to oneself need to use email protocols, and place destination email addresses into actions env & actions yml, it will introduce some credentials dependencies.
I used to try to trigger a separate workflow, which will fail, so this new workflow will send notifications to all notification-registers. But this will introduce many actions-fail-count to this project, I think it is not neat.
Above all, I decide not to promote this request.
